dist: xenial
sudo: false
language: python
python:
  - "3.5"  # Need to support debian stretch for edison 32-bit installs
install:
  - python setup.py install
  - pip install pytest
script:
  - make ci-test
